# Generated by Django 5.1 on 2024-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='prénoms')),
                ('last_name', models.CharField(max_length=30, verbose_name='nom')),
                ('contact', models.CharField(max_length=15, verbose_name='contact')),
            ],
        ),
    ]
